#!/usr/bin/env bash
#Displays information about "school"

File="school"

if [[ -e "$File" ]]
then
    echo "school file exists"
    if [[ -s "$File" ]]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [[ -f "$File" ]]
    then
        echo "school is a reguar file"
    fi
else
    echo "school file does not exist"
fi
